/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez;

/**
 *
 * @author alberto
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    private AdministrarEntrenador adminEntrenador;
    private AsignarSedePartida asignarSedePartida;
    private InformacionPartidas informacionPartidas;
    private AdminGerentesView adminGerentesView;
    private MorososView morososView;
    private AsignarResponsable asignarResponsable;
    private IntroducirResultados introducirResultados;
    private RealizarReserva realizarReserva;
    private AdminJugadorView adminJugadorView;
    
    public AdminView() {
        adminEntrenador = new AdministrarEntrenador(this);
        asignarSedePartida = new AsignarSedePartida(this);
        informacionPartidas = new InformacionPartidas(this);
        adminGerentesView = new AdminGerentesView(this);
        morososView = new MorososView(this);
        asignarResponsable = new AsignarResponsable(this);
        introducirResultados = new IntroducirResultados(this);
        realizarReserva = new RealizarReserva(this);
        adminJugadorView = new AdminJugadorView(this);
        
        morososView.pack();
        informacionPartidas.pack();
        asignarSedePartida.pack();
        adminEntrenador.pack();
        asignarResponsable.pack();
        introducirResultados.pack();
        adminJugadorView.pack();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelView = new javax.swing.JPanel();
        jButtonSede = new javax.swing.JButton();
        jButtonInfoPartidas = new javax.swing.JButton();
        jButtonAnyadirGerente = new javax.swing.JButton();
        jButtonAnyadirEntrenador = new javax.swing.JButton();
        jButtonMultasMorosos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSede.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonSede.setText("Elegir sede para partida");
        jButtonSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSedeActionPerformed(evt);
            }
        });

        jButtonInfoPartidas.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonInfoPartidas.setText("Ver info partidas para cada jugador");
        jButtonInfoPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoPartidasActionPerformed(evt);
            }
        });

        jButtonAnyadirGerente.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonAnyadirGerente.setText("Administrar gerente");
        jButtonAnyadirGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirGerenteActionPerformed(evt);
            }
        });

        jButtonAnyadirEntrenador.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonAnyadirEntrenador.setText("Administrar Entrenador");
        jButtonAnyadirEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirEntrenadorActionPerformed(evt);
            }
        });

        jButtonMultasMorosos.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonMultasMorosos.setText("Pago multas de morosos");
        jButtonMultasMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultasMorososActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton1.setText("Asignar Responsable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton2.setText("Introducir Resultados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton3.setText("Realizar Reserva");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton4.setText("Administrar jugadores");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInfoPartidas, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jButtonAnyadirGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnyadirEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMultasMorosos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonSede)
                .addGap(18, 18, 18)
                .addComponent(jButtonInfoPartidas)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnyadirGerente)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnyadirEntrenador)
                .addGap(18, 18, 18)
                .addComponent(jButtonMultasMorosos)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInfoPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoPartidasActionPerformed

        setVisible(false);
        informacionPartidas.setVisible(true);
    }//GEN-LAST:event_jButtonInfoPartidasActionPerformed

    private void jButtonSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSedeActionPerformed

        setVisible(false);
        asignarSedePartida.setVisible(true);
    }//GEN-LAST:event_jButtonSedeActionPerformed

    private void jButtonAnyadirGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirGerenteActionPerformed
        setVisible(false);
        adminGerentesView.setVisible(true);
    }//GEN-LAST:event_jButtonAnyadirGerenteActionPerformed

    private void jButtonAnyadirEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirEntrenadorActionPerformed
       this.setVisible(false);
       adminEntrenador.setVisible(true);
    }//GEN-LAST:event_jButtonAnyadirEntrenadorActionPerformed

    private void jButtonMultasMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultasMorososActionPerformed
        
        setVisible(false);
        morososView.setVisible(true);
    }//GEN-LAST:event_jButtonMultasMorososActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        setVisible(false);
        asignarResponsable.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        introducirResultados.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        realizarReserva.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        setVisible(false);
        adminJugadorView.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAnyadirEntrenador;
    private javax.swing.JButton jButtonAnyadirGerente;
    private javax.swing.JButton jButtonInfoPartidas;
    private javax.swing.JButton jButtonMultasMorosos;
    private javax.swing.JButton jButtonSede;
    private javax.swing.JPanel jPanelView;
    // End of variables declaration//GEN-END:variables
}
