/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez_View;

import Controlador.Administrador;
import ligaajedrez_Model.LigaAjedrez;

/**
 *
 * @author alberto
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    private AdministrarEntrenador adminEntrenador;
    private AsignarSedePartida asignarSedePartida;
    private InformacionPartidas informacionPartidas;
    private AdminGerentesView adminGerentesView;
    private MorososView morososView;
    private AsignarResponsable asignarResponsable;
    private IntroducirResultados introducirResultados;
    private RealizarReserva realizarReserva;
    private AdminJugadorView adminJugadorView;
    private LigaAjedrez liga;
    private ApuntarseTorneo apTorneo;
    private Administrador admin;
    
    public AdminView(LigaAjedrez liga,Administrador admin) {
        this.admin = admin;
        this.liga = liga;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelView = new javax.swing.JPanel();
        jButtonSede = new javax.swing.JButton();
        jButtonInfoPartidas = new javax.swing.JButton();
        jButtonAnyadirGerente = new javax.swing.JButton();
        jButtonAnyadirEntrenador = new javax.swing.JButton();
        jButtonMultasMorosos = new javax.swing.JButton();
        jButtonAsignarRes = new javax.swing.JButton();
        jButtonIntroRes = new javax.swing.JButton();
        jButtonRealizarReserva = new javax.swing.JButton();
        jButtonAdminJug = new javax.swing.JButton();
        jButtonAptTorneo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSede.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonSede.setText("Elegir sede para partida");
        jButtonSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSedeActionPerformed(evt);
            }
        });

        jButtonInfoPartidas.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonInfoPartidas.setText("Ver info partidas para cada jugador");
        jButtonInfoPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoPartidasActionPerformed(evt);
            }
        });

        jButtonAnyadirGerente.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonAnyadirGerente.setText("Administrar gerente");
        jButtonAnyadirGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirGerenteActionPerformed(evt);
            }
        });

        jButtonAnyadirEntrenador.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonAnyadirEntrenador.setText("Administrar Entrenador");
        jButtonAnyadirEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirEntrenadorActionPerformed(evt);
            }
        });

        jButtonMultasMorosos.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonMultasMorosos.setText("Pago multas de morosos");
        jButtonMultasMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultasMorososActionPerformed(evt);
            }
        });

        jButtonAsignarRes.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonAsignarRes.setText("Asignar Responsable");
        jButtonAsignarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarResActionPerformed(evt);
            }
        });

        jButtonIntroRes.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonIntroRes.setText("Introducir Resultados");
        jButtonIntroRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntroResActionPerformed(evt);
            }
        });

        jButtonRealizarReserva.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonRealizarReserva.setText("Realizar Reserva");
        jButtonRealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarReservaActionPerformed(evt);
            }
        });

        jButtonAdminJug.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonAdminJug.setText("Administrar jugadores");
        jButtonAdminJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminJugActionPerformed(evt);
            }
        });

        jButtonAptTorneo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButtonAptTorneo.setText("Apuntarse torneo");
        jButtonAptTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAptTorneoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInfoPartidas, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jButtonAnyadirGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnyadirEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMultasMorosos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAsignarRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIntroRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRealizarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdminJug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAptTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButtonAptTorneo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSede)
                .addGap(18, 18, 18)
                .addComponent(jButtonInfoPartidas)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnyadirGerente)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnyadirEntrenador)
                .addGap(18, 18, 18)
                .addComponent(jButtonMultasMorosos)
                .addGap(18, 18, 18)
                .addComponent(jButtonAsignarRes)
                .addGap(18, 18, 18)
                .addComponent(jButtonIntroRes)
                .addGap(18, 18, 18)
                .addComponent(jButtonRealizarReserva)
                .addGap(18, 18, 18)
                .addComponent(jButtonAdminJug)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInfoPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoPartidasActionPerformed

        setVisible(false);
        informacionPartidas = new InformacionPartidas(this,liga,admin);
        informacionPartidas.setVisible(true);
    }//GEN-LAST:event_jButtonInfoPartidasActionPerformed

    private void jButtonSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSedeActionPerformed

        setVisible(false);
        asignarSedePartida = new AsignarSedePartida(this,liga,admin);
        asignarSedePartida.setVisible(true);
    }//GEN-LAST:event_jButtonSedeActionPerformed

    private void jButtonAnyadirGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirGerenteActionPerformed
        setVisible(false);
        adminGerentesView = new AdminGerentesView(this, liga,admin);
        adminGerentesView.setVisible(true);
    }//GEN-LAST:event_jButtonAnyadirGerenteActionPerformed

    private void jButtonAnyadirEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirEntrenadorActionPerformed
       this.setVisible(false);
       adminEntrenador = new AdministrarEntrenador(this,liga,admin);
       adminEntrenador.setVisible(true);
    }//GEN-LAST:event_jButtonAnyadirEntrenadorActionPerformed

    private void jButtonMultasMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultasMorososActionPerformed
        
        setVisible(false);
        morososView = new MorososView(this,admin);
        morososView.setVisible(true);
    }//GEN-LAST:event_jButtonMultasMorososActionPerformed

    private void jButtonAsignarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarResActionPerformed
        
        setVisible(false);
        asignarResponsable = new AsignarResponsable(this,admin);
        asignarResponsable.setVisible(true);
    }//GEN-LAST:event_jButtonAsignarResActionPerformed

    private void jButtonIntroResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntroResActionPerformed
        setVisible(false);
        introducirResultados = new IntroducirResultados(this,liga,admin);
        introducirResultados.setVisible(true);
    }//GEN-LAST:event_jButtonIntroResActionPerformed

    private void jButtonRealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarReservaActionPerformed
        setVisible(false);
        realizarReserva = new RealizarReserva(this,admin);
        realizarReserva.setVisible(true);
    }//GEN-LAST:event_jButtonRealizarReservaActionPerformed

    private void jButtonAdminJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminJugActionPerformed
        
        setVisible(false);
        adminJugadorView = new AdminJugadorView(this,liga,admin);
        adminJugadorView.setVisible(true);
    }//GEN-LAST:event_jButtonAdminJugActionPerformed

    private void jButtonAptTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAptTorneoActionPerformed
        this.setVisible(false);
        try {
            apTorneo = new ApuntarseTorneo(this,liga,admin);
            apTorneo.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonAptTorneoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdminJug;
    private javax.swing.JButton jButtonAnyadirEntrenador;
    private javax.swing.JButton jButtonAnyadirGerente;
    private javax.swing.JButton jButtonAptTorneo;
    private javax.swing.JButton jButtonAsignarRes;
    private javax.swing.JButton jButtonInfoPartidas;
    private javax.swing.JButton jButtonIntroRes;
    private javax.swing.JButton jButtonMultasMorosos;
    private javax.swing.JButton jButtonRealizarReserva;
    private javax.swing.JButton jButtonSede;
    private javax.swing.JPanel jPanelView;
    // End of variables declaration//GEN-END:variables
}
