/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez_View;

import java.util.ArrayList;
import javax.swing.JFrame;
import ligaajedrez_Model.Jugador;
import ligaajedrez_Model.LigaAjedrez;
import ligaajedrez_Model.Torneo;

/**
 *
 * @author Gor
 */
public class ApuntarseTorneo extends javax.swing.JFrame {

    /**
     * Creates new form ApuntarseTorneo
     */
    
    private LigaAjedrez liga;
    JFrame vAnterior;
    protected ArrayList<Torneo> listaTorneos = new ArrayList<Torneo>();
    private Jugador jugador1;
    
    public ApuntarseTorneo(javax.swing.JFrame vAnterior ,LigaAjedrez liga) {
        jugador1 = new Jugador("joselo", "fernandez", "X2252013V", "625302312", "24", "Principiante", "Valencia");      //Jugador de prueba.
        this.liga = liga;
        liga.anyadirJugadores(jugador1);       
        this.vAnterior = vAnterior;
        initComponents();
        jComboBoxRes.removeAllItems();
        
        listaTorneos = liga.consultarTorneo();
        for(Torneo lTorneos : listaTorneos)
            jComboBoxRes.addItem(lTorneos.getCiudad());
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPrg = new javax.swing.JLabel();
        jComboBoxRes = new javax.swing.JComboBox<>();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPrg.setText("¿A que torneo te quieres apuntar?");

        jComboBoxRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxResActionPerformed(evt);
            }
        });

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrg)
                        .addGap(41, 41, 41)
                        .addComponent(jComboBoxRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAtras)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonConfirmar)
                        .addGap(34, 34, 34)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrg)
                    .addComponent(jComboBoxRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonAtras))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.setVisible(false);
        vAnterior.setVisible(true);
        jComboBoxRes.removeAllItems();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
         for(Torneo lT: listaTorneos)
            if(lT.getCiudad() == jComboBoxRes.getSelectedItem())
                liga.anyadirJugadorTorneo(lT,jugador1);
        this.setVisible(false);
        vAnterior.setVisible(true);
        jComboBoxRes.removeAllItems();
        
        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jComboBoxResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxResActionPerformed
        
    }//GEN-LAST:event_jComboBoxResActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxRes;
    private javax.swing.JLabel jLabelPrg;
    // End of variables declaration//GEN-END:variables
}
