package ligaajedrez_View;


import java.util.ArrayList;
import javax.swing.JFrame;
import ligaajedrez_Model.Jugador;
import ligaajedrez_Model.LigaAjedrez;
import ligaajedrez_Model.Torneo;
import ligaajedrez_View.AdminView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class IntroducirResultados extends javax.swing.JFrame {

    /**
     * Creates new form introducirResultados
     */
    JFrame vAnterior;
    private LigaAjedrez liga;
    protected ArrayList<Jugador> listaJugadores = new ArrayList<Jugador>();
    protected ArrayList<Jugador> listaJugadores2 = new ArrayList<Jugador>();
    
    
    public IntroducirResultados(javax.swing.JFrame vAnterior,LigaAjedrez liga) {
        this.liga = liga;
        this.vAnterior = vAnterior;
        initComponents();
        
        listaJugadores = liga.consultarJugadores();
        for(Jugador j : listaJugadores)
            jComboBoxJugador1.addItem(j.getsNmb());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelJugador1 = new javax.swing.JLabel();
        jLabelJugador2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxJugador1 = new javax.swing.JComboBox<>();
        jComboBoxJugador2 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabelGanador = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jComboBoxGanador = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jButtonAtras = new javax.swing.JButton();
        jButtonContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introducir Resultados");
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        jLabelJugador1.setText("Jugador 1");
        jPanel4.add(jLabelJugador1);

        jLabelJugador2.setText("Jugador 2");
        jPanel4.add(jLabelJugador2);

        jPanel2.add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxJugador1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxJugador1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBoxJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJugador1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxJugador1);

        jComboBoxJugador2.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJugador2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxJugador2);

        jPanel2.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabelGanador.setText("GANADOR");
        jPanel6.add(jLabelGanador);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxGanador.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxGanador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugador 1", "Jugador 2" }));
        jPanel7.add(jComboBoxGanador);

        jPanel2.add(jPanel7);

        jPanel1.add(jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAtras.setText("ATRAS");
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAtras);

        jButtonContinuar.setText("CONTINUAR");
        jButtonContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonContinuar);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        setVisible(false);
        vAnterior.setVisible(true);
        jComboBoxJugador2.removeAllItems();
        listaJugadores2.clear();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        setVisible(false);
        vAnterior.setVisible(true);
        jComboBoxJugador2.removeAllItems();
        listaJugadores2.clear();
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jComboBoxJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJugador1ActionPerformed
        String uno = (String) jComboBoxJugador1.getSelectedItem();
        
        listaJugadores2 = liga.consultarEnfrentamiento(uno);
        // --> enseñarle depuracion al profesor.
        for(Jugador j : listaJugadores2)
            jComboBoxJugador2.addItem(j.getsNmb());
       
    }//GEN-LAST:event_jComboBoxJugador1ActionPerformed

    private void jComboBoxJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJugador2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JComboBox<String> jComboBoxGanador;
    private javax.swing.JComboBox<String> jComboBoxJugador1;
    private javax.swing.JComboBox<String> jComboBoxJugador2;
    private javax.swing.JLabel jLabelGanador;
    private javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
