package ligaajedrez_View;

import ligaajedrez_Model.Jugador ;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class RegistrarJugador extends javax.swing.JFrame {

    /**
     * Creates new form registrarJugador
     */
    JFrame vAnterior;
    JFrame vPrincipal;
    private String sNmb, sApe, sTel, sEdad, sDNI, sElo ;
    private Jugador jugador ;
    
    public RegistrarJugador(javax.swing.JFrame vAnterior, javax.swing.JFrame vPrincipal) {
        this.vAnterior = vAnterior;
        this.vPrincipal = vPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelElo = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jComboBoxElo = new javax.swing.JComboBox<>();
        jTextFieldEdad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonAtras = new javax.swing.JButton();
        jButtonContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(200, 200, 200));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre);

        jLabelApellidos.setText("Apellidos");
        jPanel1.add(jLabelApellidos);
        jPanel1.add(jTextFieldNombre);
        jPanel1.add(jTextFieldApellidos);

        jLabelDNI.setText("DNI");
        jPanel1.add(jLabelDNI);

        jLabelTelefono.setText("Teléfono");
        jPanel1.add(jLabelTelefono);
        jPanel1.add(jTextFieldDNI);
        jPanel1.add(jTextFieldTelefono);

        jLabelElo.setText("Nivel de Habilidad");
        jPanel1.add(jLabelElo);

        jLabelEdad.setText("Fecha nacimiento");
        jPanel1.add(jLabelEdad);

        jComboBoxElo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Experto" }));
        jPanel1.add(jComboBoxElo);
        jPanel1.add(jTextFieldEdad);

        jPanel3.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));

        jButtonAtras.setText("ATRAS");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAtras);

        jButtonContinuar.setText("CONTINUAR");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonContinuar);

        jPanel3.add(jPanel2);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        
        setVisible(false);
        vAnterior.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        sNmb = jTextFieldNombre.getText() ;
        sApe = jTextFieldApellidos.getText() ;
        sTel = jTextFieldTelefono.getText() ;
        sDNI = jTextFieldDNI.getText() ;
        sEdad = jTextFieldEdad.getText() ;
        
        switch (jComboBoxElo.getSelectedIndex()) {
                    case 0:
                        sElo = "Principiante";
                        break;
                    case 1:
                        sElo = "Intermedio";
                        break;
                    case 2:
                        sElo = "Experto";
                        break;
                    default:
                        sElo = "Principiante";
                        break;
                }
        jugador = new Jugador(sNmb, sApe, sTel, sDNI, sEdad, sElo) ;
        
        setVisible(false);
        vPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JComboBox<String> jComboBoxElo;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelElo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
