/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez_View;

import Controlador.Administrador;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ligaajedrez_Model.Factory;
import ligaajedrez_Model.Gerente;
import ligaajedrez_Model.LigaAjedrez;

/**
 *
 * @author Gor
 */
public class AnyadirGerente extends javax.swing.JFrame {

    /**
     * Creates new form AnyadirGerente
     */
    JFrame vAnterior;
    JFrame vPrincipal;
    private LigaAjedrez liga ;
    private String sDNI ;
    private Gerente gerente ;
    private String sNmb, sNom, sIRPF, sClb ;
    private boolean bCmp = false ;
    private Administrador admin;
    
    private ArrayList<String> listaArg = new ArrayList<String>() ;
    private ArrayList<String> listaClubsVacio = new ArrayList<String>() ;
    public AnyadirGerente(javax.swing.JFrame vAnterior, javax.swing.JFrame vPrincipal, LigaAjedrez liga, Administrador admin) {
        this.admin = admin;
        this.vAnterior = vAnterior;
        this.vPrincipal = vPrincipal;
        this.liga = liga ;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDNI = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNomina = new javax.swing.JLabel();
        jLabelIRPF = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldIRPF = new javax.swing.JTextField();
        jTextFieldNomina = new javax.swing.JTextField();
        jLabelClub = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldClub = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDNI.setText("DNI:");

        jLabelNombre.setText("Nombre");

        jLabelNomina.setText("Nomina");

        jLabelIRPF.setText("IRPF");

        jLabelClub.setText("Club actual/Nuevo Club");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDNI)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelNomina)
                            .addComponent(jLabelIRPF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNomina)
                                    .addComponent(jTextFieldIRPF)))
                            .addComponent(jTextFieldNombre))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonBuscar)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelClub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jTextFieldClub, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAtras)
                .addGap(41, 41, 41)
                .addComponent(jButtonConfirmar)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomina)
                    .addComponent(jTextFieldNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIRPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIRPF))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelClub))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonAtras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        if(bCmp)
            liga.cambiarClubGerente(gerente, sClb) ;
        
        else{
            jTextFieldNombre.setEditable(true) ;
            jTextFieldNomina.setEditable(true) ;
            jTextFieldIRPF.setEditable(true) ;
            jTextFieldClub.setEditable(true) ;
            
            sNmb = jTextFieldNombre.getText() ;
            sNom = jTextFieldNomina.getText() ;
            sIRPF = jTextFieldIRPF.getText() ;
            sClb = jTextFieldClub.getText() ;
            sDNI = jTextFieldDNI.getText() ;
            
            Factory fac = new Factory() ;
            listaArg.add(sNom) ;
            listaArg.add(sIRPF) ;
            listaArg.add(sClb) ;
            gerente = (Gerente) fac.crearPersona(3, sNmb, sDNI, listaArg, listaClubsVacio) ;
            listaArg.clear() ;
            
            try {
                admin.anyadirGerente(gerente);
            } catch (Exception e) {
                System.out.println(e);
            }
            
        }
        
        jTextFieldClub.setEditable(true) ;
        jTextFieldDNI.setEditable(true) ;
        jTextFieldIRPF.setEditable(true) ;
        jTextFieldNombre.setEditable(true) ;
        jTextFieldNomina.setEditable(true) ;
        
        jTextFieldClub.setText("") ;
        jTextFieldDNI.setText("") ;
        jTextFieldIRPF.setText("") ;
        jTextFieldNombre.setText("") ;
        jTextFieldNomina.setText("") ; 
        this.setVisible(false);
        vPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        jTextFieldClub.setEditable(true) ;
        jTextFieldDNI.setEditable(true) ;
        jTextFieldIRPF.setEditable(true) ;
        jTextFieldNombre.setEditable(true) ;
        jTextFieldNomina.setEditable(true) ;
        
        jTextFieldClub.setText("") ;
        jTextFieldDNI.setText("") ;
        jTextFieldIRPF.setText("") ;
        jTextFieldNombre.setText("") ;
        jTextFieldNomina.setText("") ;
        
        setVisible(false);
        vAnterior.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        sDNI = jTextFieldDNI.getText() ;
        gerente = admin.buscarGerente(sDNI);
        
        
        if(!(sDNI.equals("")))
            gerente = admin.buscarGerente(sDNI);
            
        else
            JOptionPane.showMessageDialog(null, "DNI no introducido") ;
        
        if(gerente != null){
            jTextFieldNombre.setEditable(false) ;
            jTextFieldNomina.setEditable(false) ;
            jTextFieldIRPF.setEditable(false) ;
            jTextFieldClub.setEditable(false) ;
            
            jTextFieldNombre.setText(gerente.getsNmb()) ;
            jTextFieldNomina.setText(gerente.getsNom()) ;
            jTextFieldIRPF.setText(gerente.getsIRPF()) ;
            jTextFieldClub.setText(gerente.getsClb()) ; 
        } 
        
        jTextFieldNombre.setEditable(true) ;
        jTextFieldNomina.setEditable(true) ;
        jTextFieldIRPF.setEditable(true) ;
        jTextFieldClub.setEditable(true) ;
            
        bCmp = true ;
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelClub;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelIRPF;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNomina;
    private javax.swing.JTextField jTextFieldClub;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldIRPF;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNomina;
    // End of variables declaration//GEN-END:variables
}
