/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ligaajedrez_View;

import Controlador.Administrador;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ligaajedrez_Model.Entrenador;
import ligaajedrez_Model.Factory;
import ligaajedrez_Model.LigaAjedrez;

/**
 *
 * @author alberto
 */
public class RegEntrenadorView extends javax.swing.JFrame {

    /**
     * Creates new form RegEntrenadorView
     */
    JFrame vAnterior;
    JFrame vPrincipal;
    private LigaAjedrez liga ;
    private String sDNI ;
    private Entrenador entrenador ;
    private String sNmb, sApe, sFec, sTel ;
    private ArrayList<String> listaClubsEntrenador= new ArrayList<String>() ;
    private ArrayList<String> listaArg= new ArrayList<String>() ;
    private boolean bCmp = false ;
    private Administrador admin;
    public RegEntrenadorView(javax.swing.JFrame vAnterior,javax.swing.JFrame principal,LigaAjedrez liga, Administrador admin) {
        this.admin = admin;
        this.vAnterior = vAnterior;
        this.vPrincipal = principal;
        this.liga = liga ;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelView = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelClubs = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldClubs = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNombre.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelApellidos.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabelApellidos.setText("Apellidos:");

        jLabelFecha.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabelFecha.setText("Fecha nacimiento:");

        jLabelDNI.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabelDNI.setText("DNI:");

        jLabelTelefono.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabelTelefono.setText("Telefóno:");

        jLabelClubs.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabelClubs.setText("Clubes:");

        jTextFieldNombre.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jTextFieldApellidos.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jTextFieldFecha.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jTextFieldDNI.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jTextFieldTelefono.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jTextFieldClubs.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Separar los clubes con /, por ejemplo: CDA Paterna/CA Godella/");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelViewLayout.createSequentialGroup()
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelViewLayout.createSequentialGroup()
                        .addComponent(jLabelTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTelefono))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelViewLayout.createSequentialGroup()
                        .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelViewLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelApellidos))
                            .addGroup(jPanelViewLayout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelViewLayout.createSequentialGroup()
                        .addComponent(jLabelClubs)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldClubs))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelViewLayout.createSequentialGroup()
                        .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelViewLayout.createSequentialGroup()
                                .addComponent(jLabelFecha)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelViewLayout.createSequentialGroup()
                                .addComponent(jLabelDNI)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelViewLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDNI)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelViewLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonBuscar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidos))
                .addGap(18, 18, 18)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClubs)
                    .addComponent(jTextFieldClubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonRegistrar))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        jTextFieldDNI.setEditable(true) ;
        jTextFieldNombre.setEditable(true) ;
        jTextFieldApellidos.setEditable(true) ;
        jTextFieldFecha.setEditable(true) ;
        jTextFieldTelefono.setEditable(true) ;
        jTextFieldClubs.setEditable(true) ;
        
        jTextFieldDNI.setText("") ;
        jTextFieldNombre.setText("") ;
        jTextFieldApellidos.setText("") ;
        jTextFieldFecha.setText("") ;
        jTextFieldTelefono.setText("") ;
        jTextFieldClubs.setText("") ;
        
        this.setVisible(false);
        vAnterior.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        int iCnt = 0 ;
        String sClb = "" ;
        
        if(bCmp){
            jTextFieldNombre.setEditable(true) ;
            jTextFieldApellidos.setEditable(true) ;
            jTextFieldFecha.setEditable(true) ;
            jTextFieldTelefono.setEditable(true) ;
            
            sNmb = jTextFieldNombre.getText() ;
            sApe = jTextFieldApellidos.getText() ;
            sFec = jTextFieldFecha.getText() ;
            sDNI = jTextFieldDNI.getText() ;
            sTel = jTextFieldTelefono.getText() ;
            
            /*while(iCnt < jTextFieldClubs.getText().length()){
                while(jTextFieldClubs.getText().charAt(iCnt) != '/'){
                    sClb += jTextFieldClubs.getText().charAt(iCnt) ;
                    iCnt++ ;
                }*/
                listaClubsEntrenador.add(sClb) ;
            //}
            
            Factory fac = new Factory() ;
            listaArg.add(sApe) ;
            listaArg.add(sFec) ;
            listaArg.add(sTel) ;
            entrenador = (Entrenador) fac.crearPersona(2, sNmb, sDNI, listaArg, listaClubsEntrenador) ;
            listaArg.clear() ;
            try {
                admin.anyadirEntrenador(entrenador);
            } catch (Exception e) {
                System.out.println(e);
            }
            
        }
        else
            JOptionPane.showMessageDialog(null, "Debes buscar primero por el DNI") ;
        
        
        jTextFieldDNI.setEditable(true) ;
        jTextFieldNombre.setEditable(true) ;
        jTextFieldApellidos.setEditable(true) ;
        jTextFieldFecha.setEditable(true) ;
        jTextFieldTelefono.setEditable(true) ;
        jTextFieldClubs.setEditable(true) ;
        
        jTextFieldDNI.setText("") ;
        jTextFieldNombre.setText("") ;
        jTextFieldApellidos.setText("") ;
        jTextFieldFecha.setText("") ;
        jTextFieldTelefono.setText("") ;
        jTextFieldClubs.setText("") ;
        
        this.setVisible(false);
        vPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String sClubs = "" ;
        sDNI = jTextFieldDNI.getText() ;
        
        if(!(sDNI.equals("")))
            entrenador = admin.buscarEntrenador(sDNI);
            
        else
            JOptionPane.showMessageDialog(null, "DNI no introducido") ;
        
        if(entrenador.getsDNI() != null){
            jTextFieldNombre.setEditable(false) ;
            jTextFieldApellidos.setEditable(false) ;
            jTextFieldFecha.setEditable(false) ;
            jTextFieldTelefono.setEditable(false) ;
            
            jTextFieldNombre.setText(entrenador.getsNmb()) ;
            jTextFieldApellidos.setText(entrenador.getsApe()) ;
            jTextFieldFecha.setText(entrenador.getsFec()) ;
            jTextFieldTelefono.setText(entrenador.getsTel()) ;
            
            /*for(int i=0; i<entrenador.getlistaClubsEntrenador().size(); i++){
                sClubs = entrenador.getlistaClubsEntrenador().get(i) + "/" ;
            }*/
            jTextFieldClubs.setText(sClubs) ;
            
        }   
        bCmp = true ;
    }//GEN-LAST:event_jButtonBuscarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelClubs;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldClubs;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
